export {default as Contacts} from './Contacts'
export {default as CreateAccount} from './Register'
export {default as DetailsPage} from './DetailsPage'
export {default as Login} from './Login'
export {default as Plans} from './Plans'
export {default as VipTips} from './VipTips'
export {default as OnBoardPage} from './OnBoardPage'
export {default as AuthLogin} from '../Auth/AuthLogin'