export default {
    splashScreenIcon:require('../assets/splashScreenImg/AppIcon.png'),
    HomeIcon:require('../assets/icons/home.png'),
    ProfileIcon:require('../assets/icons/profile.png'),
    speakerIcon:require('../assets/icons/speaker.png'),
    AppName:require('../assets/AppIcons/AppName.png'),
    headerIcon:require('../assets/AppIcons/bet_zone_logo2.png'),
    AppImg:require('../assets/AppIcons/AppImg.png'),
    PhoneIcon:require('../assets/icons/phone.png'),
    TelephoneIcon:require('../assets/icons/telephone.png'),
    starsIcon:require('../assets/icons/stars.png'),
    VipTipsIcon:require('../assets/icons/vip_tips.png'),
    // VipTipsIcon:require('../assets/icons/viptips.svg'),
    mikeIcon:require('../assets/icons/mike.png'),
    publicIcon:require('../assets/icons/public.png'),
    telegramIcon:require('../assets/icons/telegram.png'),
    whatsappIcon:require('../assets/icons/whatsapp.png'),
    backIcon:require('../assets/Image/back.png'),
    AdminUsersIcon:require('../assets/icons/lucide_users.png'),
    footballImg:require('../assets/Image/football.webp'),
}